services:
  nginx:
    image: nginx:alpine
    container_name: city-lab-nginx
    restart: unless-stopped
    working_dir: /var/www/city-lab
    volumes:
      - ./:/var/www/city-lab
      - ./docker/nginx/city-lab-local.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - postgres
    depends_on:
      - php
      - postgres
    ports:
      - "127.0.0.1:${NGINX_PORT:-8091}:80"

  redis:
    container_name: city-lab-redis
    restart: unless-stopped
    build: ./docker/redis
    volumes:
      - redis_city_lab:/data
    ports:
      - "127.0.0.1:6391:6379"

  php:
    container_name: city-lab-php
    restart: unless-stopped
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/city-lab
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini
    working_dir: /var/www/city-lab
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    ports:
      - "127.0.0.1:9096:9000"

  postgres:
    container_name: city-lab-postgres
    restart: unless-stopped
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE:-city_lab_db}
      POSTGRES_USER: ${DB_USERNAME:-city_lab_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres_city_lab:/data/postgres
    ports:
      - "127.0.0.1:5491:5432"

volumes:
  postgres_city_lab:
    driver: local
  redis_city_lab:
    driver: local
